name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Traemos el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Damos permisos de ejecución al script
      - name: Hacer index.sh ejecutable
        run: chmod +x index.sh

      # 3) Ejecutamos nuestro script
      - name: Ejecutar index.sh (server)
        run: bash index.sh # con run se ejecuta un comando directamente en el runner (server)

      - name: Setup py
        uses: actions/setup-python@v4 # con uses se usa una accion predefinida que se puede encontrar en GitHub marketplace
        with:
          python-version: "3.x"

      - run: python deploy.py

